# Mod Info
mod_version=0.0.1
mod_group_id=com.dhj.hiresshot
mod_id=hiresshot
mod_name=HiResShot

# Versions
minecraft_version=1.19.2
forge_version=1.19.2-43.5.0
# Cloth Config for 1.19.2
cloth_config_version=8.3.103

# Gradle Settings
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.caching=true
loom.platform = forge